name       : python-qt6
version    : 6.5.1
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt6/PyQt6-6.5.1.tar.gz : e166a0568c27bcc8db00271a5043936226690b6a4a74ce0a5caeb408040a97c3
homepage   : https://www.riverbankcomputing.com/software/pyqt/
license    : GPL-3.0-or-later
component  : programming.python
summary    : A set of Python bindings for Qt6
description: |
    Python bindings for the Qt6 cross platform application toolkit.
builddeps  :
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WebChannel)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - designer6
    - pyqt-builder
    - python-opengl
    - python-ply
    - python-pyqt6-sip
    - python-sip
rundeps    :
    - python3-dbus
    - python-pyqt6-sip
setup      : |
    sip-build \
        --confirm-license \
        --no-make \
        --qmake=/usr/bin/qmake6
build      : |
    %make -C build
install    : |
    %make_install -C build INSTALL_ROOT="$installdir"
    %python3_compile
