name       : python-qt6
version    : 6.3.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt6/PyQt6-6.3.0.tar.gz : 4fd85dcb15ea4e734b6e4e216fe9a6246779761edaf2cf7c0cce1a2303a8d31b
homepage   : https://www.riverbankcomputing.com/software/pyqt/
license    : GPL-3.0-or-later
component  : programming.python
summary    : A set of Python bindings for Qt6
description: |
    Python bindings for the Qt6 cross platform application toolkit.
builddeps  :
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WebChannel)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - designer6
    - pyqt-builder
    - python-opengl
    - python-ply
    - python-pyqt6-sip
    - python-sip
rundeps    :
    - python3-dbus
    - python-pyqt6-sip
setup      : |
    sip-build \
        --confirm-license \
        --no-make \
        --qmake=/usr/bin/qmake6
build      : |
    %make -C build
install    : |
    %make_install -C build INSTALL_ROOT="$installdir"
    %python3_compile
