name       : python-qt6
version    : 6.2.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt6/PyQt6-6.2.1.tar.gz : d603a5c8effccc9174b3f43834256401a61ea40f2338306ca22fb6a1e870b89c
license    : GPL-3.0-or-later
component  : programming.python
summary    : A set of Python bindings for Qt6
description: |
    python-qt6 are the Python3 bindings for Qt6.
builddeps  :
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - pyqt-builder
    - python-opengl
    - python-pyqt6-sip
    - python-sip
rundeps    :
    - python3-dbus
    - python-pyqt6-sip
setup      : |
    sip-build \
        --confirm-license \
        --no-make \
        --qmake=/usr/bin/qmake6
build      : |
    %make -C build
install    : |
    %make_install -C build INSTALL_ROOT="$installdir"
    %python3_compile
